Licoreando/urls.py
#encoding:utf-8
from django.contrib import admin
from django.urls import path

from licor import views as lview
from usuario import views as uview


urlpatterns = [
    path('', lview.index),
    path('admin/', admin.site.urls),
    path('licor/search', lview.buscarLicor),
    path('user/register', uview.registro),
    path('user/login', uview.loginUsuario),
    path('user/logout', uview.logoutUsuario),
    path('user/forms', uview.formularios),
    path('user/recomendation', uview.recomendaciones)
]

licor/models.py
from django.db import models

class Licor(models.Model):
    id = models.AutoField(primary_key=True)
    codigoReferencia = models.TextField(blank=True,null=True)
    titulo = models.TextField(blank=True,null=True)
    descripcion = models.TextField(blank=True,null=True)
    precio = models.FloatField(blank=True,null=True)
    origen = models.TextField(blank=True,null=True)
    cantidad = models.TextField(blank=True,null=True) #Volumen o peso
    graduacion = models.FloatField(blank=True,null=True)
    urlProducto = models.URLField(unique=True)
    urlImagen = models.URLField(blank=True,null=True)
    enStock = models.BooleanField()
   
class Categoria(models.Model):
    nombre = models.TextField(unique=True)
    licor = models.ManyToManyField(Licor, blank=True)
    

usuario/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

# Create your models here.
class Formulario(models.Model):
    usuario = models.OneToOneField(User, blank = False, null = False, on_delete= models.CASCADE)
    comentario = models.TextField(blank = True, null = True)
    precioMinimo = models.FloatField(blank = True, null = True)
    precioMaximo = models.FloatField(blank = True, null = True)
    graduacionMinima = models.FloatField(blank = True, null = True)
    graduacionMaxima = models.FloatField(blank = True, null = True)

class Recomendaciones(models.Model):
    recomendado = models.IntegerField(blank = False, null = False)
    formulario = models.ForeignKey(Formulario,blank = False, null = False, on_delete = models.CASCADE)
    
class PuntuacionCategoriaLicor(models.Model):
    licor = models.TextField()
    puntuacion = models.IntegerField(validators= [MinValueValidator(0), MaxValueValidator(10)])
    formulario = models.ForeignKey(Formulario,blank = False, null = False, on_delete = models.CASCADE)
    
class PuntuacionOrigenLicor(models.Model):
    origen = models.TextField()
    puntuacion = models.IntegerField(validators= [MinValueValidator(0), MaxValueValidator(10)])
    formulario = models.ForeignKey(Formulario,blank = False, null = False, on_delete = models.CASCADE)

class PuntuacionMarcaLicor(models.Model):
    marca =models.TextField()
    puntuacion = models.IntegerField(validators= [MinValueValidator(0), MaxValueValidator(10)])
    formulario = models.ForeignKey(Formulario,blank = False, null = False, on_delete = models.CASCADE)

usuario/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db.models.query import QuerySet
from django.utils.translation import gettext_lazy as _

from usuario.models import Formulario


class Registro(forms.Form):
    Username = forms.CharField(required=False)
    Nombre = forms.CharField(max_length=30)
    Apellido = forms.CharField(max_length=60)
    Email = forms.CharField(required=False)
    Contraseña1 = forms.CharField(widget=forms.PasswordInput,label="Contraseña")
    Contraseña2 = forms.CharField(widget=forms.PasswordInput,label="Repetir contraseña")
   
    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('Username')
        password1 = cleaned_data.get('Contraseña1')
        password2 = cleaned_data.get('Contraseña2')

        if not password1 == password2:
            raise forms.ValidationError(
                _("La contraseña no coincide"),
                code='not_matching_passwords'
            )
        try:
            User.objects.get(username=username)
            raise forms.ValidationError(
                _("Ya existe un usuario con ese nombre"),
                code='username_must_unique')
        except ObjectDoesNotExist:
            pass


class Login(forms.Form):
    usuario = forms.CharField(max_length=30)
    contraseña = forms.CharField(max_length=30, widget=forms.PasswordInput)    
 
    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('Usuario')
        password = cleaned_data.get('Contraseña')
        hashed_password = make_password(password)
        try:
            user = User.objects.filter(username=username, password=hashed_password)
        except ObjectDoesNotExist:
            raise forms.ValidationError(_("Esta cuenta no existe"),
                code='not_existent_account')
            
class FormularioPreferencias(forms.Form):
    precioMinimo = forms.FloatField(required=False, label="Precio Mínimo")
    precioMaximo = forms.FloatField(required=False, label="Precio Máximo")
    graduacionMinima = forms.FloatField(required=False,label="Graduación Mínima")
    graduacionMaxima = forms.FloatField(required=False,label="Graduación Máxima")
    comentario = forms.CharField(widget=forms.Textarea,required=False,label="Comentario")
    licor = forms.CharField(required=False,label="Tipo de licor")
    puntuacionLicor = forms.IntegerField(required=False,min_value=0, max_value=10,label="Puntuación del licor")
    origen = forms.CharField(required=False,label="Origen")
    puntuacionOrigen = forms.IntegerField(required=False,min_value=0, max_value=10,label="Puntuación del origen")
    marca =forms.CharField(required=False,label="Marca")
    puntuacionMarca = forms.IntegerField(required=False,min_value=0, max_value=10,label="Puntuación de la marca")

usuario/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from licor.models import Licor
from recomendaciones.recomendaciones import generaRecomendaciones
from usuario.forms import Registro, Login, FormularioPreferencias
from usuario.models import Formulario, PuntuacionCategoriaLicor, \
    PuntuacionOrigenLicor, PuntuacionMarcaLicor, Recomendaciones


def registro(request):
    form = Registro()
    if request.method=='POST':
        form = Registro(request.POST)
        if form.is_valid():
            username = form.cleaned_data['Username']
            name = form.cleaned_data['Nombre']
            last_name = form.cleaned_data['Apellido']
            email = form.cleaned_data['Email']
            passw = form.cleaned_data['Contraseña1']
            user = User.objects.create_user(username=username,password=passw,email=email,first_name=name,last_name=last_name)
            formulario = Formulario.objects.create(comentario=None,precioMinimo=None,precioMaximo=None,graduacionMinima=None,graduacionMaxima=None,usuario=user)
            return redirect('/user/login')
        return render(request,'register.html', {'form':form})
    return render(request,'register.html', {'form':form})

def loginUsuario(request):
    form = Login()
    error = 'Error al hacer login, intentelo de nuevo o en caso de un fallo continuado, pongase en contacto con el administrador'
    if request.method=='POST':
        form = Login(request.POST)
        if form.is_valid():
            username = form.cleaned_data['usuario']
            password = form.cleaned_data['contraseña']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return render(request,'index.html')
            else:
                form = Login()
                return render(request,'login.html',{'form':form, "error":error})
        return render(request,'login.html', {'form':form,'error':error})
    return render(request,'login.html', {'form':form})

def formularios(request):
    user = request.user
    formulario = Formulario.objects.get(usuario=user)
    form = FormularioPreferencias(initial={'precioMinimo': formulario.precioMinimo,'precioMaximo': formulario.precioMaximo,'graduacionMinima': formulario.graduacionMinima,'graduacionMaxima': formulario.graduacionMaxima,'comentario': formulario.comentario})
    catLicor = PuntuacionCategoriaLicor.objects.filter(formulario=formulario)
    marcaLicor = PuntuacionMarcaLicor.objects.filter(formulario=formulario)
    origenLicor = PuntuacionOrigenLicor.objects.filter(formulario=formulario)
    if request.method=='POST':
        form = FormularioPreferencias(request.POST)
        if form.is_valid():
            comentario = form.cleaned_data['comentario']
            precioMinimo = form.cleaned_data['precioMinimo']
            precioMaximo = form.cleaned_data['precioMaximo']
            graduacionMinima = form.cleaned_data['graduacionMinima']
            graduacionMaxima = form.cleaned_data['graduacionMaxima']
            formulario.comentario=comentario
            formulario.precioMinimo=precioMinimo
            formulario.precioMaximo=precioMaximo
            formulario.graduacionMinima=graduacionMinima
            formulario.graduacionMaxima=graduacionMaxima
            formulario.save()
            licor = form.cleaned_data['licor']
            puntuacionL = form.cleaned_data['puntuacionLicor']
            if (licor and puntuacionL):  
                puntuacionLicor = PuntuacionCategoriaLicor.objects.create(licor=licor,puntuacion=puntuacionL,formulario=formulario)             
            origen = form.cleaned_data['origen']
            puntuacionO = form.cleaned_data['puntuacionOrigen']
            if (origen and puntuacionO):  
                puntuacionOrigen = PuntuacionOrigenLicor.objects.create(origen=origen,puntuacion=puntuacionO,formulario=formulario)
            marca =form.cleaned_data['marca']
            puntuacionM = form.cleaned_data['puntuacionMarca']
            if (marca and puntuacionM):  
                puntuacionMarca = PuntuacionMarcaLicor.objects.create(marca=marca,puntuacion=puntuacionM,formulario=formulario)
            
            generaRecomendaciones(formulario.id)
            return redirect("/user/forms")
        return render(request,'forms.html', {'form':form})
    return render(request,'forms.html', {'form':form,"catLicor":catLicor,"marcaLicor":marcaLicor,"origenLicor":origenLicor})

def recomendaciones(request):
    user = request.user
    formulario = Formulario.objects.get(usuario=user)
    recomendaciones = Recomendaciones.objects.filter(formulario=formulario)
    licores = []
    for r in recomendaciones:
        licores.append(Licor.objects.get(id=r.recomendado))
    return render(request,'recomendation.html',{'licores':licores})

@login_required
def logoutUsuario(request):
    logout(request)
    return render(request,'index.html')

usuario/templates/forms.html
<html>
<head>
<title>Formularios</title>
</head>
<body>
<header>
{% include 'header.html' %}

<div class="search">
<h1>Datos de preferencia</h1>
<p><a class="error">{{error}}</a></p>
<form id='form' method='post'>
<h3>Preferencias</h3>
{% csrf_token %}
{{form.as_p}}
<p><input type='submit' value='Guardar'/></p>
</form>
</div>

<div class="preferencias_left">
<table>
<tr>
<th>Licor</th>
<th>Puntuación</th>
</tr>
{% for cat in catLicor %}
<tr>
<td>{{cat.licor}}</td>
<td>{{cat.puntuacion}}</td>
</tr>
{%endfor%}
</table>
</div>

<div class="preferencias_center">
<table>
<tr>
<th>Origen</th>
<th>Puntuación</th>
</tr>
{% for cat in origenLicor %}
<tr>
<td>{{cat.origen}}</td>
<td>{{cat.puntuacion}}</td>
</tr>
{%endfor%}
</table>
</div>

<div class="preferencias_right">
<table>
<tr>
<th>Marca</th>
<th>Puntuación</th>
</tr>
{% for cat in marcaLicor %}
<tr>
<td>{{cat.marca}}</td>
<td>{{cat.puntuacion}}</td>
</tr>
{%endfor%}
</table>
</div>

</body>
</html>

usuario/templates/login.html
<html>
<head>
<title>Login</title>
</head>
<body>
<header>
{% include 'header.html' %}

<div class="center">
<h1>Entre en el sistema</h1>
<p><a class="error">{{error}}</a></p>
<form id='form' method='post'>
{% csrf_token %}
{{form.as_p}}
<p><input type='submit' value='Login'/></p>
</form>
</div>
</body>
</html>

usuario/templates/recomendation.html
<html>
<head>
<title>Recomendaciones</title>
</head>
<body>
<header>
{% include 'header.html' %}
<div class="titulo">
<h3>Para obtener una lista de recomendaciones, actualice su formulario</h3>
<h3>En caso de actualizar su formulario, puede tardar en realizar una recomendación efectiva</h3>
{% if not licores %}
  <h3>No hay recomendaciones disponibles, intente rellenar el formulario de preferencias</h3>
{%endif%}
</div>
{% if licores %}
<table style="width:50%" align="center" >
  <tr>
    <th>Título</th>
	  <th>Imagen</th>
    <th>Código</th> 
    <th>Descripción</th>
    <th>Precio</th>
    <th>Origen</th> 
    <th>Cantidad/Peso</th>
    <th>Graduación</th>
    <th>Categoría</th>
    <th>Enlace</th>
    <th>Stock</th>
  </tr>

{% for licor in licores %}
  <tr>
    <td>{{licor.titulo}}</td>
    <td><img src="{{licor.urlImagen}}" width="100px"/></td> 
    <td>
    {% if not licor.codigoReferencia == "" %}
    	{{licor.codigoReferencia}}</td>
    {%endif%}
    {% if licor.codigoReferencia == "" %}
    	---
    {%endif%}
    </td> 
    <td><div class="tooltip">
    {%if not licor.descripcion == "" %}
        <a class="description">Descripción</a><span class="tooltiptext">{{licor.descripcion}}</span></div></td>
    {%endif%}
    {%if licor.descripcion == "" %}
        <a>---</a></td>
    {%endif%}
    <td>
    {% if not licor.precio == "" %}
    	{{licor.precio}}€</td>
    {%endif%}
    {% if licor.precio == "" %}
    	Desconocido
    {%endif%}
    </td>
    <td>
    {% if not licor.origen == "" %}
    	{{licor.origen}}
    {%endif%}
    {% if licor.origen == "" or licor.origen == "Desconocido" %}
    	No disponible
    {%endif%}
    </td> 
    <td>
    {% if not licor.cantidad == "" %}
    	{{licor.cantidad}}</td>
    {%endif%}
    {% if licor.cantidad == "" %}
    	No disponible
    {%endif%}
    </td>
    <td>
    {% if not licor.graduacion == "" %}
    	{{licor.graduacion}}º</td>
    {%endif%}
    {% if licor.graduacion == "" %}
    	No disponible
    {%endif%}
    </td>
    <td>
    {% for cate in licor.categoria_set.all %}
    <p>{{cate.nombre}}</p>
    {% endfor %}
    </td>
    <td><a href="{{licor.urlProducto}}" target="_blank">Enlace</a></td>
    {% if licor.enStock == True %}
    	<td><a class="green">En stock</a></td>
    {%endif%}
    {% if licor.enStock == False %}
    	<td><a class="red">Sin stock</a></td>
    {%endif%}
 </tr>
{% endfor %}
</table>
{%endif%}
</body>
</html>

usuario/templates/register.html
<html>
<head>
<title>Registro</title>
</head>
<body>
<header>
{% include 'header.html' %}
<div class="center">
<h1>Registrese</h1>
<p><a class="error">{{error}}</a></p>
<form id='form' method='post'>
{% csrf_token %}
{{form.as_p}}
<p><input type='submit' value='Registrarse'/></p>
</form>
</div>
</body>
</html>